import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { prettyJson, relativeTime, summarise, topicPath, truncate } from '../format.js';
/** One table row, expanding in place to show the full decoded payload. */
export function EventRow({ event, showContract, onTopicClick }) {
    const [expanded, setExpanded] = useState(false);
    const firstTopic = event.topics[0];
    const topicLabel = firstTopic ? summarise(firstTopic) : '—';
    return (_jsxs(_Fragment, { children: [_jsxs("tr", { className: `event-row${expanded ? ' is-expanded' : ''}${event.inSuccessfulContractCall ? '' : ' is-failed'}`, onClick: () => setExpanded((v) => !v), "aria-expanded": expanded, children: [_jsx("td", { className: "col-toggle", "aria-hidden": "true", children: expanded ? '▾' : '▸' }), _jsxs("td", { className: "col-ledger", children: [_jsx("span", { className: "mono", children: event.ledger }), _jsx("span", { className: "muted small", children: relativeTime(event.ledgerClosedAt) })] }), showContract && (_jsx("td", { className: "col-contract mono", title: event.contractId, children: truncate(event.contractId) })), _jsxs("td", { className: "col-topic", children: [_jsx("button", { type: "button", className: "topic-chip", title: `Filter by "${topicLabel}"`, onClick: (e) => {
                                    e.stopPropagation();
                                    onTopicClick(topicLabel);
                                }, children: topicLabel }), event.topics.length > 1 && (_jsxs("span", { className: "muted small", title: topicPath(event.topics), children: ["+", event.topics.length - 1] }))] }), _jsxs("td", { className: "col-value", children: [_jsx("span", { className: "type-tag", children: event.value.type }), _jsx("span", { className: "mono", children: summarise(event.value) })] }), _jsx("td", { className: "col-tx mono", title: event.txHash, children: truncate(event.txHash, 6, 6) })] }), expanded && (_jsx("tr", { className: "detail-row", children: _jsx("td", { colSpan: showContract ? 6 : 5, children: _jsxs("div", { className: "detail", children: [!event.inSuccessfulContractCall && (_jsx("p", { className: "warning", children: "Emitted during a contract call that did not succeed. It is indexed for completeness, but it did not take effect on chain." })), event.decodeError && _jsxs("p", { className: "warning", children: ["Decode error: ", event.decodeError] }), _jsxs("dl", { className: "detail-meta", children: [_jsxs("div", { children: [_jsx("dt", { children: "Event id" }), _jsx("dd", { className: "mono", children: event.id })] }), _jsxs("div", { children: [_jsx("dt", { children: "Contract" }), _jsx("dd", { className: "mono", children: event.contractId })] }), _jsxs("div", { children: [_jsx("dt", { children: "Ledger" }), _jsx("dd", { className: "mono", children: event.ledger })] }), _jsxs("div", { children: [_jsx("dt", { children: "Closed at" }), _jsx("dd", { className: "mono", children: event.ledgerClosedAt })] }), _jsxs("div", { children: [_jsx("dt", { children: "Transaction" }), _jsx("dd", { className: "mono", children: event.txHash })] }), _jsxs("div", { children: [_jsx("dt", { children: "Position" }), _jsxs("dd", { className: "mono", children: ["tx ", event.transactionIndex, " / op ", event.operationIndex] })] })] }), _jsxs("section", { children: [_jsx("h4", { children: "Topics" }), _jsx("ol", { className: "topic-list", children: event.topics.map((topic, i) => (_jsxs("li", { children: [_jsx("span", { className: "type-tag", children: topic.type }), _jsx("code", { children: prettyJson(topic.value) })] }, i))) })] }), _jsxs("section", { children: [_jsxs("h4", { children: ["Value ", _jsx("span", { className: "type-tag", children: event.value.type })] }), _jsx("pre", { children: prettyJson(event.value.value) })] }), _jsxs("details", { className: "raw", children: [_jsx("summary", { children: "Raw XDR" }), _jsx("p", { className: "muted small", children: "Exactly what the network emitted. The decoded fields above are derived from these." }), _jsx("h5", { children: "Topics" }), _jsx("pre", { children: event.topicsXdr.join('\n') }), _jsx("h5", { children: "Value" }), _jsx("pre", { children: event.valueXdr })] })] }) }) }))] }));
}
